"""initial schema

Revision ID: abdc0155a1ff
Revises: 
Create Date: 2026-08-25 07:02:07.431802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abdc0155a1ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('STUDENT', 'MICRO_ENTREPRENEUR', name='usertype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assistant_conversations',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('used_insufficient_data_fallback', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_conversations_user_id'), 'assistant_conversations', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('data_type', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('borrowing_records',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('existing_loan_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_repayment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_period_months', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_borrowing_records_user_date', 'borrowing_records', ['user_id', 'record_date'], unique=False)
    op.create_index(op.f('ix_borrowing_records_user_id'), 'borrowing_records', ['user_id'], unique=False)
    op.create_table('consents',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('data_category', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consents_user_active', 'consents', ['user_id', 'is_active'], unique=False)
    op.create_index('ix_consents_user_category', 'consents', ['user_id', 'data_category'], unique=False)
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_table('credit_scores',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=32), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_scores_user_current', 'credit_scores', ['user_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_credit_scores_user_id'), 'credit_scores', ['user_id'], unique=False)
    op.create_table('expense_records',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=32), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('is_corrected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expense_records_user_date', 'expense_records', ['user_id', 'record_date'], unique=False)
    op.create_index(op.f('ix_expense_records_user_id'), 'expense_records', ['user_id'], unique=False)
    op.create_table('financial_metrics',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_cash_flow', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('savings_rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('expense_ratio', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('emergency_buffer_months', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_financial_metrics_user_created', 'financial_metrics', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_financial_metrics_user_id'), 'financial_metrics', ['user_id'], unique=False)
    op.create_table('financial_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_savings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('emergency_savings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_savings_target', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('income_records',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=32), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('is_corrected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_records_user_date', 'income_records', ['user_id', 'record_date'], unique=False)
    op.create_index(op.f('ix_income_records_user_id'), 'income_records', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('savings_records',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_savings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_savings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('emergency_savings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_savings_records_user_date', 'savings_records', ['user_id', 'record_date', 'created_at'], unique=False)
    op.create_index(op.f('ix_savings_records_user_id'), 'savings_records', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('is_corrected', sa.Boolean(), nullable=False),
    sa.Column('source_batch_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_batch', 'transactions', ['user_id', 'source_batch_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index('ix_transactions_user_type_date', 'transactions', ['user_id', 'type', 'transaction_date'], unique=False)
    op.create_table('score_factors',
    sa.Column('credit_score_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('impact', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credit_score_id'], ['credit_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_factors_credit_score_id'), 'score_factors', ['credit_score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_factors_credit_score_id'), table_name='score_factors')
    op.drop_table('score_factors')
    op.drop_index('ix_transactions_user_type_date', table_name='transactions')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index('ix_transactions_batch', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_savings_records_user_id'), table_name='savings_records')
    op.drop_index('ix_savings_records_user_date', table_name='savings_records')
    op.drop_table('savings_records')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_income_records_user_id'), table_name='income_records')
    op.drop_index('ix_income_records_user_date', table_name='income_records')
    op.drop_table('income_records')
    op.drop_table('financial_profiles')
    op.drop_index(op.f('ix_financial_metrics_user_id'), table_name='financial_metrics')
    op.drop_index('ix_financial_metrics_user_created', table_name='financial_metrics')
    op.drop_table('financial_metrics')
    op.drop_index(op.f('ix_expense_records_user_id'), table_name='expense_records')
    op.drop_index('ix_expense_records_user_date', table_name='expense_records')
    op.drop_table('expense_records')
    op.drop_index(op.f('ix_credit_scores_user_id'), table_name='credit_scores')
    op.drop_index('ix_credit_scores_user_current', table_name='credit_scores')
    op.drop_table('credit_scores')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_index('ix_consents_user_category', table_name='consents')
    op.drop_index('ix_consents_user_active', table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_borrowing_records_user_id'), table_name='borrowing_records')
    op.drop_index('ix_borrowing_records_user_date', table_name='borrowing_records')
    op.drop_table('borrowing_records')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assistant_conversations_user_id'), table_name='assistant_conversations')
    op.drop_table('assistant_conversations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
